### ISSUE TITLE
Help on evaluation！

### ISSUE THREAD

**Issue by liuxing007** [PKU-ICST-MIPL/FinePOSE_CVPR2024#3]
Great work! When evaluating the best_epoch_20_10.bin, we encountered the following issue. Could you please help resolve it, or could you inform us of the version of NumPy that was used? Thank you very much.
![图片](https://github.com/user-attachments/assets/96cd67e8-dc9f-40dc-a1e7-e682fd4351ba)

**Comment by xujinglin** [comment]
Thank you for reaching out with the issue you're facing while running the code. In my opinion, the issue might be caused by the NumPy library version you're currently using.

I recommend updating your environment, referring to the attachment, which should resolve your compatibility issues.




At 2024-09-02 10:34:53, "liuxing007" ***@***.***> wrote:

Great work! When evaluating the best_epoch_20_10.bin, we encountered the following issue. Could you please help resolve it, or could you inform us of the version of NumPy that was used? Thank you very much.
default.png (view on web)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
absl-py                   2.0.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
ca-certificates           2023.08.22           h06a4308_0    defaults
cachetools                5.3.1                    pypi_0    pypi
certifi                   2023.7.22                pypi_0    pypi
charset-normalizer        3.3.0                    pypi_0    pypi
chumpy                    0.67.5                   pypi_0    pypi
clip                      1.0                      pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
easydict                  1.11                     pypi_0    pypi
einops                    0.7.0                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
filelock                  3.12.4                   pypi_0    pypi
fonttools                 4.43.1                   pypi_0    pypi
freetype-py               2.4.0                    pypi_0    pypi
fsspec                    2023.9.2                 pypi_0    pypi
ftfy                      6.1.1                    pypi_0    pypi
google-auth               2.23.2                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.59.0                   pypi_0    pypi
huggingface-hub           0.17.3                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.31.6                   pypi_0    pypi
imageio-ffmpeg            0.4.9                    pypi_0    pypi
importlib-metadata        6.8.0                    pypi_0    pypi
importlib-resources       6.1.0                    pypi_0    pypi
ipdb                      0.13.13                  pypi_0    pypi
ipython                   8.12.3                   pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
markdown                  3.5                      pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.7.3                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    defaults
networkx                  3.1                      pypi_0    pypi
numpy                     1.24.0                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
opencv-python             4.8.1.78                 pypi_0    pypi
openssl                   1.1.1w               h7f8727e_0    defaults
packaging                 23.2                     pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.0.1                   pypi_0    pypi
pip                       23.3             py38h06a4308_0    defaults
prettytable               3.9.0                    pypi_0    pypi
prompt-toolkit            3.0.39                   pypi_0    pypi
protobuf                  4.25.2                   pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycocotools               2.0.7                    pypi_0    pypi
pyglet                    2.0.10                   pypi_0    pypi
pygments                  2.16.1                   pypi_0    pypi
pyopengl                  3.1.0                    pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
pyrender                  0.1.45                   pypi_0    pypi
python                    3.8.13               haa1d7c7_1    defaults
python-dateutil           2.8.2                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0    defaults
regex                     2023.10.3                pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
roma                      1.4.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
safetensors               0.4.0                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                60.2.0                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smplx                     0.1.28                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0    defaults
stack-data                0.6.3                    pypi_0    pypi
tensorboard               2.10.0                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorboardx              2.6.2.2                  pypi_0    pypi
timm                      0.4.12                   pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    defaults
tomli                     2.0.1                    pypi_0    pypi
torch                     1.10.1+cu111             pypi_0    pypi
torchaudio                0.10.1+cu111             pypi_0    pypi
torchvision               0.11.2+cu111             pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
traitlets                 5.13.0                   pypi_0    pypi
transforms3d              0.4.1                    pypi_0    pypi
trimesh                   4.0.2                    pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
urllib3                   2.0.6                    pypi_0    pypi
wcwidth                   0.2.8                    pypi_0    pypi
werkzeug                  3.0.0                    pypi_0    pypi
wheel                     0.41.2           py38h06a4308_0    defaults
xz                        5.4.2                h5eee18b_0    defaults
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0    defaults

**Comment by liuxing007** [comment]
Thanks!
